micronaut:
  application:
    name: ignite-client
  netty:
    event-loops:
      default:
        prefer-native-transport: true
        num-threads: ${NETTY_WORKER_THREADS_COUNT:10}
  executors:
    ignite:
      type: FIXED
      number-of-threads: ${THREAD_POOL_IGNITE_SIZE:10}
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
endpoints:
  prometheus:
    sensitive: false
  health:
    enabled: true
    sensitive: false

ignite:
  enabled: true
  peer-class-loading-enabled: true
  discovery-spi:
    kubernetes-ip-finder:
      enabled: ${K8S_IGNITE_ENABLED:false}
      namespace: ${K8S_IGNITE_NAMESPACE:}
      master-url: ${K8S_IGNITE_MASTER_URL:}
      service-name: ${K8S_IGNITE_SERVICE_NAME:}
      shared: ${K8S_IGNITE_SHARED:true}
      account-token: ${K8S_IGNITE_ACCOUNT_TOKEN:}
    static-ip-finder:
      enabled: ${STATIC_IGNITE_ENABLED:true}
      addresses: ${STATIC_IGNITE_ADDRESSES:}
      shared:  ${STATIC_IGNITE_SHARED:true}
  client-mode: true
  deployment-mode: shared
jackson:
  default-typing: java_lang_object
tracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    sampler:
      probability: ${JAEGER_PROBABILITY:1}
    sender:
      agent-host: ${JAEGER_HOST:jaeger-agent}
      agent-port: ${JAEGER_PORT:6831}
list-size : ${LIST_SIZE:1000}