micronaut:
  application:
    name: ignite-client
  server:
    port: ${PORT:8090}

ignite:
  enabled: true
  peer-class-loading-enabled: true
  discovery-spi:
    kubernetes-ip-finder:
      enabled: ${K8S_IGNITE_ENABLED:false}
      namespace: ${K8S_IGNITE_NAMESPACE:}
      master-url: ${K8S_IGNITE_MASTER_URL:}
      service-name: ${K8S_IGNITE_SERVICE_NAME:}
      shared: ${K8S_IGNITE_SHARED:true}
      account-token: ${K8S_IGNITE_ACCOUNT_TOKEN:}
    static-ip-finder:
      enabled: ${STATIC_IGNITE_ENABLED:true}
      addresses: ${STATIC_IGNITE_ADDRESSES:}
      shared:  ${STATIC_IGNITE_SHARED:true}
  client-mode: true
  deployment-mode: shared
jackson:
  default-typing: java_lang_object

deleted:
  caches: ${CACHE_FOR_REMOVE}
